name: CI for booth_algorithm unit

on:
  push:
    branches:
       - main
  pull_request:

jobs:
  vhdl-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install GHDL
        run: sudo apt update && sudo apt install -y ghdl
            
      - name: Run Simulation for booth_algorithm
        run: make clean && make all

      - name: Run Simulation for reg_booth_algorithm
        run: make clean && make TOP_LEVEL=tb_reg_booth_algorithm

